// This file is generated by Slice Machine. Update with care!

export { default as CallToAction } from './CallToAction'
export { default as FeaturedImage } from './FeaturedImage'
export { default as FeaturedProjects } from './FeaturedProjects'
export { default as List } from './List'
export { default as Nav } from './Nav'
export { default as PageTitle } from './PageTitle'
export { default as TextColumnSlice } from './TextColumnSlice'
